import { useMemo, useRef, useState } from "react";
import type { ProminenceSeries } from "../../data/contracts";

export interface ProminenceChartProps { readonly series: readonly ProminenceSeries[]; readonly selectedYear?: number; readonly onSelectedYearChange?: (year: number) => void; readonly startYear?: number; readonly endYear?: number; }
const X0 = 82; const X1 = 625; const Y0 = 30; const Y1 = 350;
const x = (year: number, start: number, end: number) => X0 + ((year - start) / (end - start)) * (X1 - X0);
const y = (value: number) => Y1 - (value / 100) * (Y1 - Y0);
const markerPath = (shape: ProminenceSeries["marker"], cx: number, cy: number) => shape === "square" ? `M${cx - 6},${cy - 6}h12v12h-12z` : shape === "triangle" ? `M${cx},${cy - 7}l7,13h-14z` : shape === "diamond" ? `M${cx},${cy - 8}l8,8-8,8-8-8z` : shape === "cross" ? `M${cx - 2},${cy - 8}h4v6h6v4h-6v6h-4v-6h-6v-4h6z` : `M${cx},${cy}m-6,0a6,6 0 1,0 12,0a6,6 0 1,0-12,0`;
const labelOffset: Record<string, number> = { "series-furality": -12, "series-anthrocon": 15, "series-midwest-furfest": 22 };

export function ProminenceChart({ series, selectedYear = 2024, onSelectedYearChange, startYear = 1994, endYear = 2026 }: ProminenceChartProps) {
  const [seriesIndex, setSeriesIndex] = useState(0); const focusRef = useRef<HTMLDivElement>(null); const year = Math.min(endYear, Math.max(startYear, selectedYear)); const active = series[seriesIndex];
  const detail = useMemo(() => { const point = active?.points.reduce((best, candidate) => !best || Math.abs(candidate.year - year) < Math.abs(best.year - year) ? candidate : best, undefined as ProminenceSeries["points"][number] | undefined); return point ? `${active.label}, ${point.year}: ${point.value} of 100 relative prominence. Confidence ${point.confidence}. ${point.basis}` : "No point available for this series."; }, [active, year]);
  const chooseSeries = (index: number) => { setSeriesIndex(Math.max(0, Math.min(series.length - 1, index))); focusRef.current?.focus(); };
  const onKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => { if (event.key === "ArrowRight") { event.preventDefault(); onSelectedYearChange?.(Math.min(endYear, year + 1)); } else if (event.key === "ArrowLeft") { event.preventDefault(); onSelectedYearChange?.(Math.max(startYear, year - 1)); } else if (event.key === "ArrowDown") { event.preventDefault(); chooseSeries(seriesIndex + 1); } else if (event.key === "ArrowUp") { event.preventDefault(); chooseSeries(seriesIndex - 1); } else if (event.key === "Home") { event.preventDefault(); onSelectedYearChange?.(startYear); } else if (event.key === "End") { event.preventDefault(); onSelectedYearChange?.(endYear); } else if (event.key === "Escape") { event.preventDefault(); focusRef.current?.blur(); } };
  return <section className="prominence-chart" aria-labelledby="prominence-chart-title"><div className="chart-heading"><div><h2 id="prominence-chart-title">Where furry lived</h2><p>Relative prominence of community spaces over time.</p></div><div className="chart-measure" aria-label="Measure: Relative prominence"><span>Measure</span><strong>Relative prominence</strong></div></div><p id="prominence-method-note" className="chart-note">Editorial 0–100 points are source-backed, nonliteral indices. They are not MAU, attendance, population, or market share.</p><div ref={focusRef} className="chart-focus" role="group" aria-label="Relative prominence timeline" aria-describedby="prominence-method-note chart-point-status" tabIndex={0} onKeyDown={onKeyDown}><svg viewBox="0 0 780 410" role="img" aria-labelledby="prominence-chart-title prominence-chart-description"><desc id="prominence-chart-description">Five source-backed editorial prominence series from 1994 to 2026 with an exact selected-year guide.</desc>{[0, 25, 50, 75, 100].map((value) => <g key={value}><line x1={X0} x2={X1} y1={y(value)} y2={y(value)} className="grid-line" /><text x={8} y={y(value) + 5} className="axis-label">{value}</text></g>)}<line x1={x(year, startYear, endYear)} x2={x(year, startYear, endYear)} y1={Y0} y2={Y1} className="year-guide" /><text x={x(year, startYear, endYear)} y={18} textAnchor="middle" className="guide-label">{year}</text>{[startYear, 2000, 2010, 2020, endYear].filter((value, index, list) => list.indexOf(value) === index).map((value) => <text key={value} x={x(value, startYear, endYear)} y={382} textAnchor="middle" className="axis-label">{value}</text>)}<line x1={X0} x2={X1} y1={Y1} y2={Y1} className="axis" />{series.map((item, index) => { const points = item.points.map((point) => `${x(point.year, startYear, endYear)},${y(point.value)}`).join(" "); const last = item.points[item.points.length - 1]; return <g key={item.id} className={`${index === seriesIndex ? "series active" : "series"} series--${item.id.replace("series-", "")}`} onClick={() => chooseSeries(index)}><polyline points={points} className={`series-line pattern-${item.pattern}`} />{item.points.map((point) => <path key={point.year} d={markerPath(item.marker, x(point.year, startYear, endYear), y(point.value))} className={`series-marker marker-${item.marker}`} />)}<text x={x(last.year, startYear, endYear) + 10} y={y(last.value) + 5 + (labelOffset[item.id] ?? 0)} className="series-label">{item.label}</text></g>; })}</svg></div><div id="chart-point-status" role="status" aria-live="polite" className="chart-status">{detail}</div><p className="keyboard-help">Focus the chart, then use Left/Right for year, Up/Down for series, Home, End, or Escape.</p></section>;
}
